version: '2'
services:

  nginx:
          build: ./nginx/
          ports:
                  - "80:80"
          volumes_from:
                  - php
          volumes:
                  - ./logs/nginx:/var/log/nginx
          links:
                  - php

  php:
          build: ./php/
          volumes:
                  - ./www:/www
                  - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
                  - ./php/php.ini:/usr/local/etc/php/php.ini
                  - ./logs/php-fpm:/var/log/php-fpm
          links:
                  - mariadb

  mariadb:
          image: mariadb
          restart: always
          volumes:
                  - ./mysql/data/:/var/lib/mysql
                  - ./mysql/initdb/:/docker-entrypoint-initdb.d
          environment:
                  MYSQL_ROOT_PASSWORD: PASSWORD
                  MYSQL_USER: admin
                  MYSQL_PASSWORD: PASSWORD
                  MYSQL_DATABASE: projectdb
          expose:
                  - "3306"

  phpmyadmin:
          image: phpmyadmin/phpmyadmin
          restart: always
          links:
                  - mariadb
          ports:
                  - 8080:80
          environment:
                  MYSQL_USERNAME: admin
                  MYSQL_ROOT_PASSWORD: PASSWORD
                  PMA_HOST: mariadb
                  PMA_ARBITRARY: 1
